### ISSUE TITLE
Update indexing and searching to shift coordinates when crossing IDL and/or PM

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1080]
## Summary
We currently index valid coordinates received strictly between -180 and 180 degrees longitude, under the assumption that Elasticsearch is treating everything as if it's in CCW order. However, even if we specify an orientation, it seems like the behavior of ES is not what we expect: https://github.com/elastic/elasticsearch/issues/35813#issuecomment-509759778, i.e., it might switch orientation if it crosses the dateline and results in a smaller polygon.

## Expected Behavior
When we cross the IDL and/or PM, we mean it! We want Elasticsearch to index what we mean. 😞 This means we need to shift one of the longitude coordinates by +/-360 degrees to make it even more clear...

## Ideas For Solution
The UI currently creates and sends an appropriately shifted request from drawn location filters. The logic appears to be:
* If crossing only PM, do nothing (-W, +E, W< E)
* If crossing only IDL, add 360 to East (+W, -E, **W > E**)
* If crossing IDL then PM, subtract 360 from West (+W, +E, **W > E**)
* If crossing PM then IDL, add 360 to East (-W, -E, **W > E**)

We should just shift the same way when indexing? 🤷‍♀

**Comment by dneufeldcu** [comment]
Historically in the geospatial community this has been handled by creating a multipart polygon split at IDL or PM. The are likely pros and cons to both approaches, let's discuss as well as evaluate whether there are other solutions that folks have come up with.

**Comment by dneufeldcu** [comment]
- [ ] update logic in ES-common, and also use it when we do geometry filters in the search api (assume CCW always - update openapi docs if needed)
- [ ] double check that after indexing fixes, verify UI displays maps correct
- [ ] do we need to shift how we display coords in the UI after, or plan on depending on analysis from registry?

**Comment by zebdelk** [comment]
After a lot of poking of geojson polygons, we've concluded we can't really know for sure what is intended by a polygon, and it doesn't make sense to only correct polygons that represent bounding boxes, but not other types.
Also, the geojson spec recommends splitting polygons into multipolygons at the antimeridian, due to interoperability issues (although at this point, shifting the coordinates works fine for us).

So here's the plan:
- [ ] update ISO parser to create appropriate multlipolygons from the bbox info (this will apply to both Indexer and Admin methods for upload)
- [ ] API will *not* restrict query coordinates to [-180, 180], to support the shifted coords option
- [ ] UI search query will be shifted, not split into multipolygon
- [ ] UI must support displaying records with multipolygons (collection details page) - note that this might take some creative work to summarize a bbox in text, or may require moving to getting that data from IM
- [ ] reduce the special handling of coordinates for display with leaflet (except for when drawing a query bbox)
- [ ] recommend SME logic be updated (see docs note for details of how)
- [ ] document (with pictures) the different options for dealing with antimeridian (shifting coords, multipolygon), and the trade-offs 
    - [ ] note that we have discussed a possibility for IM creating the alternate solution as part of analysis so different systems downstream can optimize, but we haven't written this up as a story
    - [ ] Guideline: as input (both indexing and queries), give us numerically continuous geometries at the antimeridian (OneStop should work correctly given either option, but other downstream services may or may not)
