### ISSUE TITLE
Support for time in CLI

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1167]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>STAR SME</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       query with times in addition to dates
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>limit my search results more precisely</td>
  </tr>
</table>

### Tasks
- [x] Support ISO 8601 time when using --starttime --endtime
- [ ] Test/fix short hand notation -stime -etime works as well

**Comment by StrayCat1** [comment]
Short hand flags (flags with one hyphen) can only be one letter due to constraints from the shared/generated library. 

Best we can do is create a normal flag for stime and etime, which we have. 

For ISO 8601 support - 
Added format - https://github.com/cedardevs/onestop/blob/a6f37feda8c29ad799938b8082d525f8aaf34481/cli/internal/pkg/parse/parsing.go#L129 

Test - 
https://github.com/cedardevs/onestop/blob/a6f37feda8c29ad799938b8082d525f8aaf34481/cli/internal/pkg/parse/parsing_test.go#L129
