### ISSUE TITLE
Collection results view 508 compliance

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#119]
- [x] Page announces when loading search results
- [x] Focus on Search Results heading when loaded
- [ ] Tiles are links rather than group

**Comment by zebdelk** [comment]
One of the goals of the Demo 508 search page #225 is to confirm the best way to make sure loading results is announced, and if focus should be manually changed or simply allow screen reader users to navigate to the results themselves.

Suggestions for results list:
- [ ] It should have a heading to make it easy to locate
- [ ] Results should be list items in an ordered list
- [ ] Results should be links with (if needed) truncated titles to make it easy to identify what they are (but not read exceedingly long paragraphs for each result if the metadata is less than ideal)
- [ ] consider using the aria role "main" for this section

**Comment by zebdelk** [comment]
I marked "Focus on Search Results heading when loaded" not because it's done, but because I think this should be a "won't fix". Changing the focus on screen readers can be confusing. As long as it correctly announces that the results have loaded and the heading for search results and list items are relatively straightforward to find, that's less disruptive to navigation.

**Comment by zebdelk** [comment]
- [ ] facet breadcrumbs
  - in tab order
  - accept key activation to remove facets (move focus to next focusable element?)
  - clear what they do ("remove X facet")

**Comment by zebdelk** [comment]
Closing this in favor of smaller, more specific stories. Most have been covered by other issues.
