### ISSUE TITLE
Saved search view component(s)

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1274]
Leverage list view of saved search

### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>future saved search user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
      see some initial views of saved search information
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>provide feedback early in development process</td>
  </tr>
</table>

### Tasks
- [x] Saved search view component

**Comment by StrayCat1** [comment]
We have a "user dashboard" that can read from the User API to get the user's saved search. 

Working on a button to POST a search to be saved. 

Right now we are simply saving the URL and parsing it in the UI to create the filter bubbles. However we think it makes more sense to save the redux state for the search (facets, etc) so that we do not have to parse the URL after reading from the User DB.

**Comment by StrayCat1** [comment]
<img width="759" alt="Screen Shot 2020-07-09 at 8 29 22 PM" src="https://user-images.githubusercontent.com/26884996/87336912-d5268f00-c4ff-11ea-90d3-a25b5705795a.png">
<img width="753" alt="Screen Shot 2020-07-09 at 8 29 45 PM" src="https://user-images.githubusercontent.com/26884996/87336917-d6f05280-c4ff-11ea-804e-04f4430bbfb6.png">

**Comment by StrayCat1** [comment]
Video demo - https://drive.google.com/file/d/1tFiGPLFJe4oXz28leA54v2oeZqqkXY-R/view?usp=sharing 

Ive since added a "delete" button. Working on styling, UX stuff- 

1) visually indicate that search did save
2) fetch new list of saved searches after creating or deleting one (not working for some reason)
3) provide a way for the user to name the the search

**Comment by StrayCat1** [comment]
We have a new UserDashboard component with the route `/dashboard`. 

Remaining work on these components has been broken into stories. 

Review can still occur on branch 1184-userRest, though that branch shouldn't be merged until other saved search epic stories are resolved.

**Comment by erinreeves** [comment]
This controller:
https://github.com/cedardevs/onestop/blob/53ababf4d44b0bb5fa7f5f3bd5f3f3c301172c97/client/src/components/user/dashboard/UserDashboardContainer.jsx

that and then there is a bookmark button in the collection list view

**Comment by zebdelk** [comment]
Reviewed
