### ISSUE TITLE
User/role based table

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1294]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>OneStop administrator</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       assign elevated privileges to certain users  (currently persisted in ACL) 
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>access protected endpoints on the saved search databases via the web API provided by the onestop-user application</td>
  </tr>
</table>

###
- [x] Create user table that has associated role and a reference to the user's saved search
- [ ] Part of this includes creating a /user/roles/{id} endpoint that Gateway can hit to get a user's roles.

**Comment by StrayCat1** [comment]
Status: We have a few new tables for user data-

onestop_user
onestop_role
onestop_privilege
onestop_search

And a few join tables for many to many relationships- 
onestop_user_role (user:role, M:N)
onestop_role_privilege  (role:privilege, M:N) 

On start up we load some default roles and privileges. 

That concludes the first acceptance criteria checkbox.

As I began working on the roles endpoint I realized the roles in the DB were not respected in the security annotations (Secured, PreAuthorize, PostAuthorize, etc). 

I have implemented a custom UserDetailService to map the user's privileges to their spring grant authorities, but must be missing a piece that wires that to the security annotation.

**Comment by StrayCat1** [comment]
Pushed up those new tables, controllers, and tests for the User, Role, Privileges. 
https://github.com/cedardevs/onestop/tree/1184-userRest/user/src/test/groovy/org/cedar/onestop/user
https://github.com/cedardevs/onestop/tree/1184-userRest/user/src/integrationTest/groovy/org/cedar/onestop/user
https://github.com/cedardevs/onestop/tree/1184-userRest/user/src/main/java/org/cedar/onestop/user/domain

Drafted up a diagram for easy reference- 
https://docs.google.com/drawings/d/15DLjEj9o5NzwsHxxpy98xJUhLR5L4JOS7xbtz-jUrN0/edit

That much really was the intended scope of this story. I am going one step further to integrate the ROLE table in the postgres DB with our @Secured annotations. Testing/implementing has been an obstacle, but it's the last hurdle before building some really cool user features. 

UserDetails testing and integration still in progress. Considering changing up our authentication flow just a bit so that Gatway simply passes the token response to User app using `@EnabledSsoAuthentication` and `@ResourceServer` like so - https://www.baeldung.com/spring-security-oauth2-enable-resource-server-vs-enable-oauth2-sso

Im hoping this would enable Gateway (where we would @EnableOAuth2Sso) to pass the id_token instead of the access_token (which User currently uses to hit /user_info) and then label User as an @EnableResourceServer to receive and use the id_token. 

More about the id_token here- https://developers.login.gov/oidc/#token

**Comment by StrayCat1** [comment]
Also more about resource server -https://docs.spring.io/spring-security/site/docs/5.1.x/reference/html/webflux-oauth2.html#webflux-oauth2-resource-server

and specifically validating the token coming back from login.gov (via gateway) 
https://docs.spring.io/spring-security/site/docs/5.1.x/reference/html/webflux-oauth2.html#webflux-oauth2-resource-server-jwkseturi

**Comment by dneufeldcu** [comment]
Working on initialization process for an admin user.
