### ISSUE TITLE
Update local StorageClass ReclaimPolicy to Retain

### ISSUE THREAD

**Issue by Ghebrechristos** [cedardevs/onestop#1323]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       retain my Es data 
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>keep working </td>
  </tr>
</table>

**Comment by mcquinne** [comment]
Turns out that you can't modify the `reclaimPolicy` of an existing storage class, so we'll have to make a separate one and then use it in our `Elasticsearch` manifest.

This is probably a better solution anyway though, as we can just declare it in `elastic.yaml` and it'll work for everyone, rather than making everyone manually update their default storage class.

**Comment by mcquinne** [comment]
So it's easy enough to create a new `StorageClass` which retains volumes by default, but it turns out that that doesn't get us all the way there: When you tear down Elasticsearch and then bring it back, a new `PersistentVolumeClaim` with a new UID is created, and so a new `PersistentVolume` is created as well, rather than mounting the previously-created volume.

After discussing with the team, I'm going to spend a couple days on a time-boxed exploration to figure out if there's a way to use k8s volume snapshotting and/or the CSI system to reconnect the elastic pods with their previous volumes.

**Comment by dneufeldcu** [comment]
Parallel thread - independent data loader. OBE

Explore https://github.com/elastic/cloud-on-k8s/tree/master/hack/reattach-pv

**Comment by mcquinne** [comment]
FYI came across another potential solution here: https://github.com/elastic/cloud-on-k8s/tree/master/hack/reattach-pv
