### ISSUE TITLE
AWS IaC work

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1403]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>CIRES developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       run the OneStop stack in the CIRES AWS account
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>test the whole system</td>
  </tr>
</table>

### Tasks to set up account
- Create a VPC, with:
    - DNS hostnames and DNS resolution enabled
    - Both private and public subnets available
- Create route table with:
    - local target for private CIDRs
    - associations with all private subnets
- Create security group for service endpoints with:
    - Allow all for traffic from within the VPC private CIDR
- Add service endpoints to support EKS cluster:
    - s3
    - ec2
    - ecr.api, ecr.dkr
- Add service endpoints to support application interactions:
    - sns
    - sqs
- Add Internet Gateway to allow outbound connections, e.g. to pull docker images

**Comment by mcquinne** [comment]
The CIRES AWS account has been set up with [a VPC](https://console.aws.amazon.com/vpc/home?region=us-east-1#VpcDetails:VpcId=vpc-0114c0b954bf9170c), containing both [public and private subnets](https://console.aws.amazon.com/vpc/home?region=us-east-1#subnets:VpcId=vpc-0114c0b954bf9170c;sort=tag:Name), [NAT Gateways in each public subnet](https://console.aws.amazon.com/vpc/home?region=us-east-1#NatGateways:vpcId=vpc-0114c0b954bf9170c) for external Internet communication, [a "bastion" host](https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#InstanceDetails:instanceId=i-0dee9376ac5f1e20f) that we can ssh into in order to access internal resources, and [an EKS Cluster](https://console.aws.amazon.com/eks/home?region=us-east-1#/clusters/cedar) in which to deploy our Kubernetes workloads. It turned out that the easiest way to do this was to leverage two AWS "quickstarts" to [set up the VPC](https://aws.amazon.com/quickstart/architecture/vpc/) and then [add the bastion](https://aws.amazon.com/quickstart/architecture/linux-bastion/). As a result we now also have [two CloudFormation Stacks](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks?filteringText=&filteringStatus=active&viewNested=true&hideStacks=false) to manage this infrastructure.

Going forward we should do our best **NOT** to modify the infrastructure directly and instead edit the CloudFormation templates/parameters so the process is automated and repeatable.

I've configured us all accounts on the bastion host and we should all be able to connect to the EKS cluster. Without further ado, here are the steps to do so:

1.  If you haven't logged into the AWS Console yet you will receive a separate email from me with the our console login link and your initial credentials. Log in and update your password.
2.  If you don't have an access key yet, use the AWS console to [create one for yourself](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey)
    -   Note: on the last page when you create your key you'll need to either copy/paste the secret portion somewhere or download the csv that it presents you. You will not be able to retrieve the secret again (though it is trivial to create a new access key).
3.  Log into the bastion host using your aws account name and [the instance's public IP address](https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#InstanceDetails:instanceId=i-0dee9376ac5f1e20f)
    -   For example: `ssh e_mcquinn@PUBLIC_IP`
    -   Tip: I like to add an entry to my ~/.ssh/config so I can use a more friendly name, like:
    ```
    Host cedar-devs
    HostName PUBLIC_IP
    User e_mcquinn
    ```
4.  On the bastion host, run `aws configure` and provide your access key id and secret key
    -   use us-east-1 as your default region
5.  Run `aws eks update-kubeconfig --name cedar --alias cedar`
    -   this will update your `~/.kube/config` file with the necessary details in order to connect to the [EKS cluster named cedar](https://console.aws.amazon.com/eks/home?region=us-east-1#/clusters/cedar)
6. Run `kubectl get nodes` and verify that you can see the nodes in the cluster
