### ISSUE TITLE
cedardevs cluster - Search API forward

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#1437]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>onestop user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       make requests to the search API on cedardevs.org
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>download the openapi yaml and search using the API</td>
  </tr>
</table>

https://cedardevs.org/onestop/api/search redirects to an internal hostname https://os-search/openapi.yaml

It should proxy, not redirect.

**Comment by YangusKhan** [comment]
PR with a simple solution has been created.

I have a few questions that might be more appropriate for follow-on stories or design discussions:

- Is a 302 redirect to the `openapi.yaml` file truly the most appropriate response for the root endpoint? Why not respond with the YAML file directly instead of doing a redirect? Or we could redirect to the swaggerhub page of the API?
- Should we be putting the registry API into swaggerhub like we are with the search API?

**Comment by erinreeves** [comment]
http://localhost/onestop/api/search does download the openapi.yaml
