### ISSUE TITLE
Review GEFS metadata extraction pull request

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1472]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>python client dev</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       include GEFS metadata extraction in the python client
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>expand the file formats we can expand the formats supported</td>
  </tr>
</table>

### Tasks
- [x] Review pull request from NWS data lake team member merge to master

**Comment by JeffreyHuynh1** [comment]
Committed some changes on WebPublisher.py to resolve merge conflicts to master

**Comment by JeffreyHuynh1** [comment]
Path of web-publisher-config-dev.yml has changed from onestop-clinets/onestop-python-client/config -> scripts/config

This will cause errors for the data lake team because they have defined a direct path to the web-publisher-config-dev file. 

They will need to change 
config_path = "/home/siteadm/onestop-clients/onestop-python-client/config/" on line 501 in GefsExtractor.py to 
config_path = "/home/siteadm/onestop-clients/scripts/config/
