### ISSUE TITLE
UI Design Discussion

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#198]
Prioritizing next steps - 508 compliance updates, collection view updates, facet menu, search results view. About help tweaks.

**Comment by dneufeldcu** [comment]
To determine what the specific goals of #142 are.

**Comment by ajakz** [comment]
White board UI thoughts:

We like the direction of the below wireframes for changes to the facet/filter sidebar menu and query box in the header. This distinctly separates new searches from search modification logic, making a more user-friendly experience, and gives us a lot more screen real estate for filtering options. Zeb has 508 compliance notes on several (maybe all) aspects of the landing and results views that we'll incorporate in as we work through each component. 

Priorities for stories going forward (others should review and modify my list if needed):
- Fix GCMD keyword display to a hierarchical view, defaulting to L0 and L1 keywords auto-displayed (user can dive down further). No limitations on how many levels can be expanded within the keywords menu. Part of this work would be migrating the current facet sub-menus underneath a Keywords one; Temporal and Spatial to be added later.
- In tandem with this keyword cleanup, we need to improve the accessibility of the search results page. Some concerns: screen reader should announce arrival at results page; screen reader needs to be able to access filtering menu; top-level sections of page should be grouped together for navigation (new search box, filtering options, main navigation menu, search results, etc.); option to collapse filtering menu is presented early so that screen reader doesn't get lost in it; hopefully we can find a way to just announce different filtering option types (keywords, temporal, spatial) and provide easy access to open/close/populate.
- Search results have truncated/clear to understand designations for screen reader, e.g., "Search Result 1: [Truncated title]. Click for more."
- Collection view no longer a popup, opens inline with results. Maybe a brief view (for browsing) about the collection (picture, DSMM, full title, some themes, etc.) with a link to a collection page like what currently exists outside of OS. Don't put description, citation, data access, etc. full info here -- assume user is still browsing until they proceed to the collection's actual view.
- Make that full view of collection...
- Temporal and spatial components are moved to filtering menu. Landing page and header only have query text box. It should be clear to all users that submitting new text == triggering new search. We can wait for user feedback to decide if we need an "Advanced Search" option on the landing page that returns time & space filtering options.

![image uploaded from ios 1](https://user-images.githubusercontent.com/5514537/30601422-2c5bfbae-9d1f-11e7-8db4-e3a7dc561c25.jpg)
![image uploaded from ios 2](https://user-images.githubusercontent.com/5514537/30601421-2c5735d8-9d1f-11e7-82f1-8bf05570441b.jpg)
![image uploaded from ios 3](https://user-images.githubusercontent.com/5514537/30601423-2c62d6c2-9d1f-11e7-9d54-ab540788d5bb.jpg)

**Comment by ajakz** [comment]
The wireframes that were created out of this: 
[OneStop -- Dec 2017.pdf](https://github.com/cedardevs/onestop/files/1338933/OneStop.--.Dec.2017.pdf)
