### ISSUE TITLE
SPIKE: client hardcoded path

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#302]
In order to deploy multiple versions of the stack on the CU infrastructure at the same time, we need to remove the hardcoded /onestop/api path from the client code.

We need to be sure that we don't break production deployment, which doesn't use containerization.

Potential options:
- version the API (e.g. - sciapps.colorado.edu/onestop/v1/api )

Research:
- compile in variables at build time?
- base on environment context, etc...
- what do real people do IRL?

Acceptance Criteria:
- present ideas to the team no later than Christmas

**Comment by mcquinne** [comment]
Proposed change: on app load, calculate the path the app is being hosted from, then build the path to api endpoint relative to the app's path.

e.g. if the app loads itself and sees that it's being served from `<host>/onestop/version_a/` then it'll use `<host>/onestop/version_a/api` as the base for all its api requests.

This would clearly still require modifications to the front-facing web server in order to support multiple paths proxying to multiple docker stacks... but I think this change gives us the ability to do that in the future.

**Comment by mcquinne** [comment]
Also: I came across a nice article showing some of the more advanced things we can do with setting cookies on incoming requests and then using them to decide how to handle subsequent requests. Might help us set up nginx when we get there: 

https://www.viget.com/articles/split-test-traffic-distribution-with-nginx
