### ISSUE TITLE
Map bounding box is confusing when entering text

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#430]
This is likely confusing to users, and limits what kinds of bounding boxes can effectively be searched using only text entry for location.

- [x] typing in coordinates with North < South should result in a validation error (currently N: 42, S: 40 results in the exact same bounding box as N:40, S:42)
- [x] typing in coordinates with West > East should invert the bounding box vs East > West. For example:
  - W: 80, S: -90, E: -80, N: 90 should be the opposite selection from W: -80, S: -90, E: 80, N: 90, but is currently the exact same bounding box.

**Comment by ajakz** [comment]
For the second point, as long as the polygon does NOT cross both the date line AND the prime meridian, Leaflet will draw the shape accurately. However, even if the coordinates entered/polygon drawn by the user DOES cross both lines, the underlying search AND the coordinates in the text boxes are **actually accurate**. 

This problem occurs because Leaflet will reverse the order of the coordinates to CW (we use CCW throughout, per standard) before rendering in the event the geometry crosses both lines. It appears there is no way to tell Leaflet which order the given coordinates are (or which way to generate them), which means this visual bug cannot be resolved by us. I would suggest an amendment to our Help page when we circle back to it for #363 that explains the issue.

**Comment by zebdelk** [comment]
Closing as part of the branch for #405. The remaining issue with Leaflet was reiterated in #457 to document known problems and possible solutions. We believe they are edge cases at this time.
