### ISSUE TITLE
ETL Flattened granules

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#581]
- [x] reuse logic from original flattened granule script (but without synthetic granules) to ETL
  - it should probably pull collections and granules from the search indices instead of staging
- [x] make sure flattened granule ETL is offset since it's a more intensive ETL

Note: pipelines can't currently combine multiple documents, so this is not a pipeline task

**Comment by ajakz** [comment]
Note -- I didn't end up offsetting the flattening ETL (instead it runs right after staging -> search ETL of granules & collections) since there isn't a way to determine if a scheduled ETL is presently running. This is to make sure flattening didn't happen on some but not all migrating records, which could cause some to be missed (transfer to search indices isn't guaranteed to be done in order of ascending stagedDate). That being said, flattening seems to take about twice as long as regular ETL when there are a lot of zero-granule collections to be checked the first few times, but then tapers off to be fairly quick once there are few or no records to be updated.
