### ISSUE TITLE
Entering coordinates with a '0' value are rejected from the text based coord search

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#741]
Example:
West: 0
South: 10
East: 10
North: 10

**Comment by zebdelk** [comment]
Take a look and see if the text-box is somehow interpreting "0" as null instead of a number. No idea if this is the source of the bug, but we did have issues with blank strings *not* being treated as null at one point.

Alternatively, add more tests around geoUtils, if the 0 is getting handled correctly as a number.
