### ISSUE TITLE
Go through ORR for v2.3

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#834]
See:
https://github.com/cedardevs/onestop/wiki/Release-Checklist

- [ ] Add review of feature toggle defaults to checklist

**Comment by zebdelk** [comment]
Using ANDI, I'm seeing a lot of warnings about the leaflet maps because the canvas version of those is missing an accessible name. Leaflet doesn't have any options to easily change that. I've decided to leave those alone for now, as the accessible alternative to the map is entering bounding box coordinates in the form.
