### ISSUE TITLE
OneStop documentation pointer

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#900]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>As a current user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       find the documentation that used to be on the wiki
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>continue to stay up to date on OneStop changes</td>
  </tr>
</table>

- [ ] Put top-level doc TOC in main README as well

**Comment by zebdelk** [comment]
For reviewer:

Actions taken:
- [x] turned wiki feature back on in github
- [x] deleted old documentation pages
- [x] changed [wiki home page](https://github.com/cedardevs/onestop/wiki) to refer to updated docs

I looked into ways to include the TOC in the main README, but couldn't find a way to do so that avoided manually duplicating it, which has higher risk of it getting out of sync.

**Comment by StrayCat1** [comment]
I think the quick links we have in the readme at each level are as good as a TOC. 

This looks good, calling it done!
